import type { GameDetail } from "@/features/games/types";

export const gameDetails: GameDetail[] = [
  {
    id: "btc-vol-premiere",
    title: "BTC Vol Premiere",
    subtitle: "Fast table for directional conviction and timing pressure.",
    assetPair: "BTC / USDC",
    network: "devnet",
    status: "live",
    startsAt: "2026-04-19T10:30:00.000Z",
    entryFeeUsd: 25,
    prizePoolUsd: 4800,
    playerCount: 64,
    strategyCount: 18,
    summary:
      "A short-cycle arena tuned for fast BTC positioning. Players can study open participation, prize shape, and traction before wallet wiring lands.",
    oracle: "Pyth devnet feed",
    totalVolumeUsd: 128400,
    averageExposureUsd: 2006,
    prizeDistribution: "50 / 30 / 20",
    standings: [
      {
        address: "4AL7y3b35v7oCjT6R6V8t9F9hYy4Qm2R",
        strategy: "Momentum Stack",
        pnlUsd: 1240,
        conviction: "Aggressive",
      },
      {
        address: "8nUE9i5P7iZ3V2eT6C2mA3pJ2yQ9Fw1N",
        strategy: "Delta Fade",
        pnlUsd: 880,
        conviction: "Balanced",
      },
      {
        address: "9dXQ3mLp8wKe2rH7VvT2nS4oD5yE6pUa",
        strategy: "Mean Re-entry",
        pnlUsd: 610,
        conviction: "Measured",
      },
    ],
  },
  {
    id: "sol-breakout-labs",
    title: "SOL Breakout Labs",
    subtitle: "A cleaner room for medium-duration breakout plays.",
    assetPair: "SOL / USDC",
    network: "devnet",
    status: "registration",
    startsAt: "2026-04-19T13:00:00.000Z",
    entryFeeUsd: 15,
    prizePoolUsd: 2250,
    playerCount: 38,
    strategyCount: 11,
    summary:
      "This room is aimed at pre-launch design work: who joins, what liquidity concentration looks like, and where wallet connection needs to clarify trust.",
    oracle: "Switchboard devnet feed",
    totalVolumeUsd: 50400,
    averageExposureUsd: 1326,
    prizeDistribution: "60 / 25 / 15",
    standings: [
      {
        address: "Gd1fQ8o2pM7tY6n4rV5bA1eQ3jL8sPkW",
        strategy: "Compression Break",
        pnlUsd: 0,
        conviction: "Balanced",
      },
      {
        address: "Fh3nW4r7qL5tU8v1xY2bC9mK6pA4dSeR",
        strategy: "Range Escape",
        pnlUsd: 0,
        conviction: "Measured",
      },
    ],
  },
  {
    id: "eth-macro-sprint",
    title: "ETH Macro Sprint",
    subtitle: "Settled room used to validate payout, standings, and archive states.",
    assetPair: "ETH / USDC",
    network: "devnet",
    status: "settled",
    startsAt: "2026-04-18T16:00:00.000Z",
    entryFeeUsd: 40,
    prizePoolUsd: 9600,
    playerCount: 92,
    strategyCount: 24,
    summary:
      "A completed arena showing what the settled state should communicate: winners, oracle source, and the shape of post-game analytics.",
    oracle: "Pyth devnet feed",
    totalVolumeUsd: 246000,
    averageExposureUsd: 2674,
    prizeDistribution: "45 / 30 / 15 / 10",
    standings: [
      {
        address: "Bq8rJ1mV2zX3nP4sD5fG6hK7lQ8wE9rT",
        strategy: "Carry Rotation",
        pnlUsd: 2410,
        conviction: "Balanced",
      },
      {
        address: "Dx6sP3vN9qM2aR4tW7yU1iC5oL8kJ0hF",
        strategy: "Asymmetry Sweep",
        pnlUsd: 1730,
        conviction: "Aggressive",
      },
      {
        address: "Lq2wE4rT6yU8iO1pA3sD5fG7hJ9kZ0xC",
        strategy: "Volatility Ladder",
        pnlUsd: 980,
        conviction: "Measured",
      },
    ],
  },
];
